api_platform:
    enable_swagger_ui: true
    enable_swagger: true
    enable_docs: true
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    eager_loading:
        max_joins: 100
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        jsonpatch: ['application/merge-patch+json']
